version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "scraper-translator"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-fd9edrqczc8h"
s3_prefix = "scraper-translator"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
