name: scraper-translator

on:
  push:
    branches: [ main ]

jobs:
  test-lambda:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up NodeJS
        uses: actions/setup-node/@v2
        with:
          node-version: '14'
      - run: npm install
  deploy-lambda:
    name: Deploy Scraper Translator
    runs-on: ubuntu-latest
    needs: test-lambda
    steps:
      - run: echo ${{ secrets.GOOGLE_CLOUD }} >> google_cloud_secret.json
      - uses: actions/checkout@v2
      - uses: actions/setup-node/@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          aws-region: 'us-east-1'
      - run: sam build && sam deploy --no-fail-on-empty-changeset
      - run: pwd
      - run: ls -la
      - run: sam build
      - run: cat .aws-sam/build.toml
      - run: sam deploy --no-fail-on-empty-changeset
      - run: cat samconfig.toml
